name: Test CI

on:
  push:
    branches:
      - citest

jobs:
  job1:
    runs-on: ubuntu-latest
    name: job1
    steps:
      - run: echo "job1 run"
  job2:
    runs-on: ubuntu-latest
    name: job2
    needs: job1
    steps:
      - run: echo "job2 run"
  job3:
    runs-on: ubuntu-latest
    name: job3
    needs: [job1, job2]
    if: ${{ github.event_name == 'push' }}
    steps:
      - run: echo "job3 run........."
